[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "YahooTools"
version = "0.0.0"
description = "YahooTools"
readme = "README.md"
requires-python = ">=3.8"